# Configuration file to declaratively configure labels
# Ref: https://github.com/EndBug/label-sync#Config-files

- name: backport:v2-1
  description: To be backported to v2-1
  color: '#ffd700'
- name: backport:v2-0
  description: To be backported to v2-0
  color: '#ffd700'
- name: area/adopters
  description: Flux & Flagger adopters pull requests
  color: '#00b140'
- name: area/blog
  description: Blog related issues and pull requests
  color: '#863faf'
- name: area/ecosystem
  description: Ecosystem related issues and pull requests
  color: '#1673b6'
- name: area/events
  description: Events related issues and pull requests
  color: '#29CCD3'
  aliases: ['events']
- name: area/flagger
  description: Flagger related issues and pull requests
  color: '#006b75'
- name: area/flux
  description: Flux related issues and pull requests
  color: '#c739ff'
- name: area/landing-page
  description: Landing page related issues and pull requests
  color: '#DE9AAE'
  aliases: ['landing page']
- name: area/resources
  description: Video resources related issues and pull requests
  color: '#00e54d'
- name: area/roadmap
  description: Roadmap related issues and pull requests
  color: '#00e54d'
- name: area/search
  description: Search related issues and pull requests
  color: '#DE9AAE'
  aliases: ['search']
- name: blocked/requires-dco
  description: Pull requests that must be signed
  color: '#DF007D'
  aliases: ['blocked-dco']
- name: blocked/requires-rebase
  description: Pull requests that must be rebased
  color: '#DF007D'
  aliases: ['blocked-rebase']
