baseURL = "/"
title = "Flux"
enableRobotsTXT = true
enableEmoji = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableGitInfo = true

[module]
proxy = "direct"

[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/google/docsy"
disable = false

[[module.imports.mounts]]
source = "assets/scss"
target = "assets/scss/docsy"

[[module.imports.mounts]]
source = "content"
target = "content"

[[module.imports.mounts]]
source = "static"
target = "static"

[[module.imports.mounts]]
source = "layouts"
target = "layouts"

[[module.imports.mounts]]
source = "data"
target = "data"

[[module.imports.mounts]]
source = "assets"
target = "assets"

[[module.imports.mounts]]
source = "i18n"
target = "i18n"

[[module.imports.mounts]]
source = "archetypes"
target = "archetypes"

[[module.imports.mounts]]
source = "node_modules/bootstrap"
target = "assets/vendor/bootstrap"

[[module.imports.mounts]]
source = "node_modules/@fortawesome/fontawesome-free"
target = "assets/vendor/Font-Awesome"

[[module.imports.mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/webfonts"

[[module.imports]]
path = "github.com/google/docsy/dependencies"
disable = false

[[module.imports]]
path = "github.com/mfg92/hugo-shortcode-gallery"
disable = false

[[module.mounts]]
source = "content/en"
target = "content"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "friendly"

[markup.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[languages.en.params]
languageName = "English"
languageCode = "en"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"

[permalinks]
blog = "/:section/:year/:month/:slug/"

[outputFormats.SearchIndex]
baseName = "index"
mediaType = "application/json"

[outputs]
home = [ "HTML", "SearchIndex" ]
page = [ "HTML", "SearchIndex" ]

[params]
description = "Open and extensible continuous delivery solution for Kubernetes."
copyright = "The Flux authors"
github_repo = "https://github.com/fluxcd/website"
github_branch = "main"
github_project_repo = "https://github.com/fluxcd/flux2"
slack = "https://cloud-native.slack.com/messages/flux"
support = "/support"
images = [ "img/flux-social.png" ]
algolia_docsearch = true
offlineSearch = false
version_menu = "Versions"
version = "2.2"
archived_version = false
version_menu_pagelinks = true
url_latest_version = "https://fluxcd.io/flux/"

[[params.versions]]
version = "v2.2"
url = "https://fluxcd.io"

[[params.versions]]
version = "v2.1"
url = "https://v2-1.docs.fluxcd.io"

[[params.versions]]
version = "v2.0"
url = "https://v2-0.docs.fluxcd.io"

[params.logos]
navbar = "flux-horizontal-white.png"
hero = "flux-horizontal-color.png"
footer = "flux-stacked-white.png"
cncf = "cncf-color.png"

[params.ui]
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_menu_truncate = 1_000
breadcrumb_disable = false
sidebar_search_disable = true
navbar_logo = true
footer_about_disable = false

[params.ui.readingtime]
enable = false

[params.markmap]
enable = true

[[params.links.user]]
name = "Twitter"
url = "https://twitter.com/fluxcd"
icon = "fab fa-twitter"
desc = "Follow us on Twitter to get the latest news!"

[[params.links.user]]
name = "LinkedIn"
url = "https://linkedin.com/groups/8985374"
icon = "fab fa-linkedin"
desc = "Join the Flux Community group on LinkedIn!"

[[params.links.user]]
name = "RSS Feed"
url = "/blog/index.xml"
icon = "fa fa-rss"
desc = "Subscribe to the RSS feed of our blog!"

[[params.links.user]]
name = "Support"
url = "/support"
icon = "fas fa-comments"
desc = "Subscribe to the RSS feed of our blog!"

[[params.links.developer]]
name = "Flux project on GitHub"
url = "https://github.com/fluxcd"
icon = "fab fa-github"
desc = "Development takes place here!"

[[params.links.developer]]
name = "Slack"
url = "https://cloud-native.slack.com/messages/flux"
icon = "fab fa-slack"
desc = "Chat with other project developers"

[[params.links.developer]]
name = "Developer mailing list"
url = "https://lists.cncf.io/g/cncf-flux-dev"
icon = "fa fa-envelope"
desc = "Discuss development issues around the project"

[[params.links.developer]]
name = "Flux YouTube channel"
url = "https://youtube.com/@fluxcd"
icon = "fab fa-youtube"
desc = "Watch videos about Using Flux and Flux Development"

[[menus.main]]
name = "Documentation"
url = "/flux"
weight = 10

[[menus.main]]
name = "Code of Conduct"
parent = "Project"
url = "https://github.com/fluxcd/community/blob/main/CODE_OF_CONDUCT.md"
weight = 1

[[menus.main]]
name = "Resources"
parent = "Project"
url = "/resources"
weight = 5

[[menus.main]]
name = "Support"
parent = "Project"
url = "/support"
weight = 10

[[menus.main]]
name = "Community"
parent = "Project"
url = "/community"
weight = 20

[[menus.main]]
name = "Contributing"
parent = "Project"
url = "/contributing"
weight = 30

[[menus.main]]
name = "Governance"
parent = "Project"
url = "/governance"
weight = 40

[[menus.main]]
name = "Roadmap"
parent = "Project"
url = "/roadmap"
weight = 50

[[menus.main]]
name = "Security"
parent = "Project"
url = "/security"
weight = 60

[[menus.main]]
name = "Branding"
parent = "Project"
url = "https://github.com/cncf/artwork/blob/master/examples/graduated.md#flux-logos"
weight = 9_999

[[menus.main]]
name = "Adopters"
url = "/adopters"
weight = 80

[[menus.main]]
name = "Ecosystem"
url = "/ecosystem"
weight = 90

[[menus.main]]
name = "Flagger"
url = "https://flagger.app"
weight = 100

[[menus.main]]
identifier = "Project"
name = "Project"
weight = 110
